// Language detection from Telegram WebApp
const tgUser = window.Telegram?.WebApp?.initDataUnsafe?.user;
const userLang = (tgUser?.language_code || navigator.language || 'uk').substring(0, 2);
const isEn = !['uk', 'ru', 'be'].includes(userLang);

const TRUTHS_UK = [
  "Яка найбільш безглузда річ, яку ти коли-небудь робив/робила?",
  "Який найнезручніший момент у твоєму житті?",
  "Чи є у тебе секрет, який ти нікому не розповідав/розповідала?",
  "Кого з цієї групи ти б взяв/взяла на безлюдний острів?",
  "Яка пісня є твоїм guilty pleasure?",
  "Коли ти востаннє плакав/плакала і чому?",
  "Чи є у тебе таємний талант?",
  "Яка найдивніша їжа, яку ти коли-небудь пробував/пробувала?",
  "Про що ти найбільше жалієш?",
  "Хто був твоїм першим крашем?",
  "Чи обманював/обманювала ти коли-небудь на іспиті?",
  "Яка найбільша брехня, яку ти коли-небудь казав/казала?",
  "Чи є щось, чого ти дуже боїшся?",
  "Якби ти міг/могла змінити одну річ у своєму минулому, що б це було?",
  "Що останнє ти гуглив/гуглила?",
  "Чи розмовляєш ти сам/сама з собою?",
  "Яка найдорожча річ, яку ти зламав/зламала?",
  "Чи є у тебе кумедна дитяча історія?",
  "Що тебе найбільше дратує в людях?",
  "Якби ти став/стала невидимим на один день, що б ти робив/робила?",
  "Яке твоє найбільше досягнення?",
  "Чи є у тебе неприємна звичка?",
  "Кого з відомих людей ти хотів/хотіла б зустріти?",
  "Яка найсмішніша ситуація на роботі/навчанні?",
  "Чи бачив/бачила ти коли-небудь привид?",
  "Яка найдивніша річ у твоїй пошуковій історії?",
  "Чи є у тебе фотка, яку ти нікому не покажеш?",
  "Яка найбільша сума, яку ти витрачав/витрачала за один раз?",
  "Яке твоє найнезвичайніше хобі?",
  "Який найдивніший сон ти бачив/бачила?",
  "Чи є людина, якій ти винен/винна вибачення?",
  "Що б ти зробив/зробила з мільйоном доларів?",
  "Яка найгірша порада, яку ти коли-небудь давав/давала?",
  "Яка твоя найбільша слабкість?",
  "Яке твоє перше враження було про когось із цієї групи?",
  "Який останній серіал ти дивився/дивилася до 4 ранку?",
  "Чи є у тебе таємний акаунт у соцмережах?",
  "Про кого з цієї групи ти думаєш найчастіше?",
  "Яка найсмішніша помилка в повідомленні, яку ти відправляв/відправляла?",
  "Чи маєш ти улюблену іграшку з дитинства, яку досі зберігаєш?",
  "Яке найдивніше місце, де ти засинав/засинала?",
  "Який найбільший секрет ти дізнався/дізналась випадково?",
  "Чи є людина, якій ти заздриш? Чому?",
  "Яка найсмішніша відмазка, яку ти використовував/використовувала?"
];

const TRUTHS_EN = [
  "What's the most ridiculous thing you've ever done?",
  "What's the most embarrassing moment of your life?",
  "Do you have a secret you've never told anyone?",
  "Who from this group would you take to a deserted island?",
  "What song is your guilty pleasure?",
  "When was the last time you cried and why?",
  "Do you have a hidden talent?",
  "What's the weirdest food you've ever tried?",
  "What do you regret most?",
  "Who was your first crush?",
  "Have you ever cheated on a test?",
  "What's the biggest lie you've ever told?",
  "Is there something you're really afraid of?",
  "If you could change one thing in your past, what would it be?",
  "What's the last thing you googled?",
  "Do you talk to yourself?",
  "What's the most expensive thing you've broken?",
  "Do you have a funny childhood story?",
  "What annoys you most about people?",
  "If you were invisible for a day, what would you do?",
  "What's your biggest achievement?",
  "Do you have an annoying habit?",
  "Which celebrity would you love to meet?",
  "What's the funniest situation at work or school?",
  "Have you ever seen a ghost?",
  "What's the weirdest thing in your search history?",
  "Do you have a photo you'd never show anyone?",
  "What's the most you've ever spent at once?",
  "What's your most unusual hobby?",
  "What's the weirdest dream you've had?",
  "Is there someone you owe an apology to?",
  "What would you do with a million dollars?",
  "What's the worst advice you've ever given?",
  "What's your biggest weakness?",
  "What was your first impression of someone in this group?",
  "What's the last show you binge-watched until 4 AM?",
  "Do you have a secret social media account?",
  "Who in this group do you think about most?",
  "What's the funniest texting mistake you've made?",
  "Do you still have a favorite childhood toy?",
  "What's the weirdest place you've fallen asleep?",
  "What's the biggest secret you found out by accident?",
  "Is there someone you're jealous of? Why?",
  "What's the funniest excuse you've ever used?"
];

const DARES_UK = [
  "Зроби 10 присідань прямо зараз",
  "Надішли останнє фото з галереї",
  "Напиши комплімент наступній людині в контактах",
  "Розкажи анекдот (якщо не смішний — ще один!)",
  "Зміни аватарку на найсмішнішу фотку на 1 годину",
  "Надішли голосове повідомлення зі співом",
  "Зроби селфі прямо зараз і відправ сюди",
  "Говори тільки римами наступні 5 хвилин",
  "Напиши вірш про будь-кого з цієї групи",
  "Зроби 20 стрибків на місці",
  "Надішли найстарішу фотку зі свого телефону",
  "Зроби комплімент кожному учаснику цієї групи",
  "Імітуй тварину голосовим повідомленням",
  "Намалюй портрет наступного гравця і відправ фото",
  "Протримай телефон на голові 30 секунд (фото як доказ!)",
  "Наспівай улюблену пісню голосовим",
  "Зроби фото найдивнішої речі в кімнаті",
  "Напиши вірш про себе за 2 хвилини і відправ",
  "Відправ голосове зі спробою реп-батла",
  "Зроби 30 секунд планки (фото/відео як доказ!)",
  "Запиши відео як ти танцюєш 15 секунд",
  "Зроби серйозне селфі і підпиши 'Я контролюю ситуацію'",
  "Намалюй автопортрет за 1 хвилину і відправ",
  "Зроби відео де пояснюєш квантову фізику за 15 секунд",
  "Зроби відео-привітання цій групі як ведучий новин",
  "Надішли фото свого холодильника",
  "Запиши голосове де імітуєш робота",
  "Відправ найкумедніший мем зі свого телефону",
  "Зроби 5 берпі (відео як доказ!)",
  "Зроби серйозне фото з найкумеднішим предметом поруч"
];

const DARES_EN = [
  "Do 10 squats right now",
  "Send the last photo from your gallery",
  "Send a compliment to the next person in your contacts",
  "Tell a joke (if it's not funny — tell another!)",
  "Change your avatar to the funniest photo for 1 hour",
  "Send a voice message of you singing",
  "Take a selfie right now and send it here",
  "Speak only in rhymes for the next 5 minutes",
  "Write a poem about someone in this group",
  "Do 20 jumping jacks",
  "Send the oldest photo on your phone",
  "Give a compliment to every person in this group",
  "Imitate an animal in a voice message",
  "Draw a portrait of the next player and send it",
  "Balance your phone on your head for 30 seconds (photo proof!)",
  "Sing your favorite song in a voice message",
  "Take a photo of the weirdest thing in the room",
  "Write a poem about yourself in 2 minutes and send it",
  "Send a voice message trying to rap battle",
  "Hold a plank for 30 seconds (photo/video proof!)",
  "Record a video of you dancing for 15 seconds",
  "Take a serious selfie with caption 'I have the situation under control'",
  "Draw a self-portrait in 1 minute and send it",
  "Record a video explaining quantum physics in 15 seconds",
  "Record a video greeting this group as a news anchor",
  "Send a photo of your fridge",
  "Record a voice message imitating a robot",
  "Send the funniest meme from your phone",
  "Do 5 burpees (video proof!)",
  "Take a serious photo with the funniest object nearby"
];

const NEVERS_UK = [
  "Я ніколи не... прогулював/прогулювала роботу/пари",
  "Я ніколи не... засинав/засинала в громадському транспорті",
  "Я ніколи не... надсилав/надсилала повідомлення не тій людині",
  "Я ніколи не... гуглив/гуглила себе",
  "Я ніколи не... їв/їла їжу, яку впустив/впустила на підлогу",
  "Я ніколи не... плакав/плакала від фільму",
  "Я ніколи не... обманував/обманювала батьків",
  "Я ніколи не... розмовляв/розмовляла з тваринами як з людьми",
  "Я ніколи не... робив/робила вигляд, що не чую когось",
  "Я ніколи не... дивився/дивилася серіал цілу ніч",
  "Я ніколи не... забував/забувала чийсь день народження",
  "Я ніколи не... притворявся/притворялася хворим, щоб не йти кудись",
  "Я ніколи не... танцював/танцювала перед дзеркалом",
  "Я ніколи не... читав/читала чужі повідомлення",
  "Я ніколи не... їв/їла сніг",
  "Я ніколи не... зустрічав/зустрічала знаменитість",
  "Я ніколи не... ходив/ходила в піжамі на вулицю",
  "Я ніколи не... співав/співала в душі",
  "Я ніколи не... ламав/ламала кістку",
  "Я ніколи не... блокував/блокувала когось у месенджері",
  "Я ніколи не... їв/їла о 3 ночі",
  "Я ніколи не... дивився/дивилася на чужий телефон",
  "Я ніколи не... забував/забувала де поклав/поклала телефон",
  "Я ніколи не... робив/робила вигляд, що знаю про що мова",
  "Я ніколи не... ходив/ходила в кіно один/одна",
  "Я ніколи не... робив/робила татуювання",
  "Я ніколи не... стрибав/стрибала з висоти",
  "Я ніколи не... вигравав/вигравала в лотерею",
  "Я ніколи не... спав/спала на роботі/парах",
  "Я ніколи не... підслуховував/підслуховувала чужу розмову",
  "Я ніколи не... забував/забувала ім'я людини одразу після знайомства",
  "Я ніколи не... випадково лайкав/лайкала стару фотку, гортаючи чийсь профіль",
  "Я ніколи не... їздив/їздила зайцем у транспорті",
  "Я ніколи не... притворявся/притворялася, що не бачу когось знайомого на вулиці",
  "Я ніколи не... гуглив/гуглила симптоми і діагностував/діагностувала собі хворобу",
  "Я ніколи не... плакав/плакала від сміху",
  "Я ніколи не... робив/робила покупки о 3 ночі онлайн",
  "Я ніколи не... співав/співала караоке перед незнайомцями"
];

const NEVERS_EN = [
  "Never have I ever... skipped work or class",
  "Never have I ever... fallen asleep on public transport",
  "Never have I ever... sent a message to the wrong person",
  "Never have I ever... googled myself",
  "Never have I ever... eaten food I dropped on the floor",
  "Never have I ever... cried from a movie",
  "Never have I ever... lied to my parents",
  "Never have I ever... talked to animals like they're people",
  "Never have I ever... pretended not to hear someone",
  "Never have I ever... binge-watched a show all night",
  "Never have I ever... forgotten someone's birthday",
  "Never have I ever... faked being sick to avoid something",
  "Never have I ever... danced in front of a mirror",
  "Never have I ever... read someone else's messages",
  "Never have I ever... eaten snow",
  "Never have I ever... met a celebrity",
  "Never have I ever... gone outside in pajamas",
  "Never have I ever... sung in the shower",
  "Never have I ever... broken a bone",
  "Never have I ever... blocked someone on a messenger",
  "Never have I ever... eaten at 3 AM",
  "Never have I ever... looked at someone else's phone screen",
  "Never have I ever... forgot where I put my phone",
  "Never have I ever... pretended to know what was going on",
  "Never have I ever... gone to the movies alone",
  "Never have I ever... gotten a tattoo",
  "Never have I ever... jumped from a height",
  "Never have I ever... won a lottery",
  "Never have I ever... fallen asleep at work or in class",
  "Never have I ever... eavesdropped on someone's conversation",
  "Never have I ever... forgotten someone's name right after meeting them",
  "Never have I ever... accidentally liked an old photo while stalking someone",
  "Never have I ever... rode public transport without a ticket",
  "Never have I ever... pretended not to see someone I know on the street",
  "Never have I ever... googled symptoms and diagnosed myself",
  "Never have I ever... cried from laughing",
  "Never have I ever... online shopped at 3 AM",
  "Never have I ever... sung karaoke in front of strangers"
];

const RATHERS_UK = [
  ["Мати суперсилу літати", "Бути невидимим"],
  ["Ніколи не їсти солодке", "Ніколи не їсти солоне"],
  ["Знати всі мови світу", "Вміти грати на всіх інструментах"],
  ["Жити без інтернету", "Жити без кондиціонера"],
  ["Бути найрозумнішим", "Бути найкрасивішим"],
  ["Подорожувати в минуле", "Подорожувати в майбутнє"],
  ["Мати 10 близьких друзів", "Мати 1000 знайомих"],
  ["Завжди говорити правду", "Завжди брехати"],
  ["Жити в горах", "Жити на березі моря"],
  ["Бути вічно молодим", "Бути вічно багатим"],
  ["Ніколи не спати", "Спати 16 годин на добу"],
  ["Вміти читати думки", "Вміти телепортуватися"],
  ["Жити без музики", "Жити без кіно"],
  ["Мати ідеальну пам'ять", "Мати ідеальну інтуїцію"],
  ["Бути найвідомішою людиною", "Бути найщасливішою людиною"],
  ["Їсти тільки піцу все життя", "Їсти тільки суші все життя"],
  ["Жити у 2226 році", "Жити у 1826 році"],
  ["Бути директором компанії", "Бути вільним мандрівником"],
  ["Мати ідеальне тіло", "Мати ідеальний розум"],
  ["Жити без смартфона", "Жити без комп'ютера"],
  ["Завжди бути в центрі уваги", "Бути непомітним/непомітною"],
  ["Мати безлімітні гроші", "Мати безлімітний час"],
  ["Виграти Оскар", "Виграти Нобелівську премію"],
  ["Жити 200 років звичайним", "Жити 80 років суперлюдиною"],
  ["Знати всі секрети всіх людей", "Щоб ніхто не знав твоїх секретів"],
  ["Жити в космосі", "Жити на дні океану"],
  ["Бути найкращим у одній справі", "Бути непоганим у всьому"],
  ["Жити в світі без брехні", "Жити в світі без злочинів"],
  ["Вміти зупиняти час", "Вміти перемотувати час назад"],
  ["Завжди бути ситим", "Завжди бути виспаним"],
  ["Жити без соцмереж", "Жити без ігор"],
  ["Бути кішкою", "Бути собакою"],
  ["Вміти дихати під водою", "Вміти не спати"],
  ["Жити в Середземʼї", "Жити у всесвіті Гаррі Поттера"],
  ["Завжди знати правду", "Вміти переконати будь-кого"],
  ["Бути найкращим танцюристом", "Бути найкращим співаком"],
  ["Ніколи не чекати в чергах", "Ніколи не стояти в пробках"],
  ["Мати ідеальний слух", "Мати ідеальний зір"],
  ["Жити в майбутньому без технологій", "Жити в минулому з сучасними технологіями"]
];

const RATHERS_EN = [
  ["Have the superpower of flight", "Be invisible"],
  ["Never eat sweets again", "Never eat salty food again"],
  ["Know every language in the world", "Play every musical instrument"],
  ["Live without internet", "Live without AC"],
  ["Be the smartest person", "Be the most attractive person"],
  ["Travel to the past", "Travel to the future"],
  ["Have 10 close friends", "Have 1000 acquaintances"],
  ["Always tell the truth", "Always lie"],
  ["Live in the mountains", "Live by the sea"],
  ["Be forever young", "Be forever rich"],
  ["Never sleep", "Sleep 16 hours a day"],
  ["Read minds", "Teleport anywhere"],
  ["Live without music", "Live without movies"],
  ["Have perfect memory", "Have perfect intuition"],
  ["Be the most famous person", "Be the happiest person"],
  ["Eat only pizza forever", "Eat only sushi forever"],
  ["Live in the year 2226", "Live in the year 1826"],
  ["Be a CEO", "Be a free traveler"],
  ["Have a perfect body", "Have a perfect mind"],
  ["Live without a smartphone", "Live without a computer"],
  ["Always be the center of attention", "Be invisible in every room"],
  ["Have unlimited money", "Have unlimited time"],
  ["Win an Oscar", "Win a Nobel Prize"],
  ["Live 200 years as a normal person", "Live 80 years as a superhuman"],
  ["Know everyone's secrets", "Have nobody know yours"],
  ["Live in outer space", "Live at the bottom of the ocean"],
  ["Be the best at one thing", "Be decent at everything"],
  ["Live in a world without lies", "Live in a world without crime"],
  ["Stop time", "Rewind time"],
  ["Always be full", "Always be well-rested"],
  ["Live without social media", "Live without games"],
  ["Be a cat", "Be a dog"],
  ["Breathe underwater", "Never need sleep"],
  ["Live in Middle-earth", "Live in the Harry Potter universe"],
  ["Always know the truth", "Be able to convince anyone"],
  ["Be the best dancer", "Be the best singer"],
  ["Never wait in line", "Never be stuck in traffic"],
  ["Have perfect hearing", "Have perfect vision"],
  ["Live in the future without technology", "Live in the past with modern tech"]
];

// Active question sets based on language
const TRUTHS = isEn ? TRUTHS_EN : TRUTHS_UK;
const DARES = isEn ? DARES_EN : DARES_UK;
const NEVERS = isEn ? NEVERS_EN : NEVERS_UK;
const RATHERS = isEn ? RATHERS_EN : RATHERS_UK;
